/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTC8 (number 53), led1
  @{ */
#define BOARD_INITPINS_led1_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_led1_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_led1_PIN 8U     /*!<@brief PORTC pin index: 8 */
                                       /* @} */

/*! @name PORTC9 (number 54), led2
  @{ */
#define BOARD_INITPINS_led2_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_led2_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_led2_PIN 9U     /*!<@brief PORTC pin index: 9 */
                                       /* @} */

/*! @name PORTC10 (number 55), led3
  @{ */
#define BOARD_INITPINS_led3_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_led3_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_led3_PIN 10U    /*!<@brief PORTC pin index: 10 */
                                       /* @} */

/*! @name PORTC11 (number 56), led4
  @{ */
#define BOARD_INITPINS_led4_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_led4_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_led4_PIN 11U    /*!<@brief PORTC pin index: 11 */
                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
